version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "dependencies"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "actions"
  - package-ecosystem: "npm"
    target-branch: "dependencies"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "yarn"
      - "dependencies"
