version: "3.8"

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=aninotes
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"