name: CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-use-cases:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql://postgres:pass123@localhost:5432/aninotes

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: npx prisma migrate deploy
      - name: Run Use Cases
        run: yarn test
      - name: Run e2e
        run: yarn test:e2e
