on:
  push:
    branches:
      - main
      - dependencies
      - '!release-please-**'

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
